package view;


import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JColorChooser;
import set_icon.MyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DoThanhDat
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    MyEvent myEvent;
    Color c;
    Graphics g;
    Point p1, p2;
    boolean flagPen, flagEraser, flagShape;
    Color colorOld;
    
    public Main() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("My Paint - Design by Do Thanh Dat");
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        jtbnChooseColor.setForeground(Color.WHITE);
        
        c = Color.BLACK;
        g = jpnPaint.getGraphics();
        jtbnChooseColor.setBackground(c);
        
        myEvent = new MyEvent();
        myEvent.setMyIconTitle(this);
        
        flagPen = false;
        flagEraser = false;
        flagShape = false;
        
        turnOnOffJRadio(false);
        jradFill.setEnabled(false);
        
        colorOld = jbtnClear.getBackground();
        myEvent.setIcon(jbtnEraser, jbtnPen, jbtnShape);
    }

    private void turnOnOffJRadio(boolean check)
    {
        jradLine.setEnabled(check);
        jradRectangle.setEnabled(check);
        jradRoundRec.setEnabled(check);
        jradOval.setEnabled(check);
        jradDraw.setEnabled(check);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtbnChooseColor = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnEraser = new javax.swing.JButton();
        jbtnPen = new javax.swing.JButton();
        jradLine = new javax.swing.JRadioButton();
        jradRectangle = new javax.swing.JRadioButton();
        jradRoundRec = new javax.swing.JRadioButton();
        jradOval = new javax.swing.JRadioButton();
        jradDraw = new javax.swing.JRadioButton();
        jradFill = new javax.swing.JRadioButton();
        jpnPaint = new javax.swing.JPanel();
        jsldSize = new javax.swing.JSlider();
        jbtnShape = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbnChooseColor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbnChooseColor.setText("Choose Color");
        jtbnChooseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnChooseColorActionPerformed(evt);
            }
        });

        jbtnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnEraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEraserActionPerformed(evt);
            }
        });

        jbtnPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPenActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradLine);
        jradLine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradLine.setSelected(true);
        jradLine.setText("Line");
        jradLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradLineActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradRectangle);
        jradRectangle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradRectangle.setText("Rectangle");
        jradRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradRectangleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradRoundRec);
        jradRoundRec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradRoundRec.setText("RoundRec");
        jradRoundRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradRoundRecActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradOval);
        jradOval.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jradOval.setText("Oval");
        jradOval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradOvalActionPerformed(evt);
            }
        });

        buttonGroup2.add(jradDraw);
        jradDraw.setSelected(true);
        jradDraw.setText("Draw");
        jradDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradDrawActionPerformed(evt);
            }
        });

        buttonGroup2.add(jradFill);
        jradFill.setText("Fill");
        jradFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradFillActionPerformed(evt);
            }
        });

        jpnPaint.setBackground(new java.awt.Color(255, 255, 255));
        jpnPaint.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jpnPaintMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpnPaintMouseMoved(evt);
            }
        });
        jpnPaint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnPaintMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpnPaintMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jpnPaintLayout = new javax.swing.GroupLayout(jpnPaint);
        jpnPaint.setLayout(jpnPaintLayout);
        jpnPaintLayout.setHorizontalGroup(
            jpnPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnPaintLayout.setVerticalGroup(
            jpnPaintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        jsldSize.setMajorTickSpacing(10);
        jsldSize.setMaximum(45);
        jsldSize.setMinimum(1);
        jsldSize.setMinorTickSpacing(2);
        jsldSize.setPaintLabels(true);
        jsldSize.setPaintTicks(true);
        jsldSize.setValue(1);

        jbtnShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShapeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Point:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnPaint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtbnChooseColor)
                            .addComponent(jbtnClear))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnPen)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnEraser))
                            .addComponent(jbtnShape))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradLine)
                                .addGap(18, 18, 18)
                                .addComponent(jradRoundRec)
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jradFill)
                                    .addComponent(jradDraw))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradRectangle)
                                .addGap(18, 18, 18)
                                .addComponent(jradOval)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                                .addComponent(jsldSize, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnEraser, jbtnPen, jbtnShape});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnClear, jtbnChooseColor});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jradLine, jradOval, jradRectangle, jradRoundRec});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jradDraw, jradFill});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnEraser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtbnChooseColor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnPen)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jradLine)
                                .addComponent(jradRoundRec)
                                .addComponent(jradDraw)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jradRectangle)
                                    .addComponent(jradOval)
                                    .addComponent(jradFill)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnShape)
                                    .addComponent(jbtnClear)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jsldSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jpnPaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnEraser, jbtnPen, jbtnShape});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnClear, jtbnChooseColor});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jradLine, jradOval, jradRectangle, jradRoundRec});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jradDraw, jradFill});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPenActionPerformed
        jbtnEraser.setBackground(colorOld);
        jbtnPen.setBackground(Color.GREEN);
        jbtnShape.setBackground(colorOld);
        jradFill.setEnabled(false);
        
        turnOnOffJRadio(false);
        jsldSize.setValue(1);
        myEvent.setMyPen(jpnPaint);
        flagPen = true;
        flagEraser = false;
        flagShape = false;
    }//GEN-LAST:event_jbtnPenActionPerformed

    private void jbtnEraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEraserActionPerformed
        jbtnEraser.setBackground(Color.GREEN);
        jbtnPen.setBackground(colorOld);
        jbtnShape.setBackground(colorOld);
        
        turnOnOffJRadio(false);
        jsldSize.setValue(1);
        myEvent.setMyEraser(jpnPaint);
        jradFill.setEnabled(false);
        flagPen = false;
        flagEraser = true;
        flagShape = false;
    }//GEN-LAST:event_jbtnEraserActionPerformed

    private void jtbnChooseColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnChooseColorActionPerformed
        c = JColorChooser.showDialog(null, "Chooser color", c);
        jtbnChooseColor.setBackground(c);
    }//GEN-LAST:event_jtbnChooseColorActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        repaint();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jpnPaintMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPaintMousePressed
        p1 = evt.getPoint();
    }//GEN-LAST:event_jpnPaintMousePressed

    private void jpnPaintMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPaintMouseDragged
        if(flagPen)
        {
            p2 = evt.getPoint();
            Graphics2D g1 = (Graphics2D) g;
            g1.setStroke(new BasicStroke(jsldSize.getValue()));
            g.setColor(c);
            g.drawLine(p1.x, p1.y, p2.x, p2.y);
            p1 = p2;
        }
        
        if(flagEraser)
        {
            p2 = evt.getPoint();
            Graphics2D g1 = (Graphics2D) g;
            g1.setStroke(new BasicStroke(jsldSize.getValue()));
            g.setColor(Color.WHITE);
            g.drawLine(p1.x, p1.y, p2.x, p2.y);
            p1 = p2;
        }
    }//GEN-LAST:event_jpnPaintMouseDragged

    private void jradRoundRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradRoundRecActionPerformed
        jradFill.setEnabled(true);
    }//GEN-LAST:event_jradRoundRecActionPerformed

    private void jradRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradRectangleActionPerformed
        jradFill.setEnabled(true);
    }//GEN-LAST:event_jradRectangleActionPerformed

    private void jradOvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradOvalActionPerformed
        jradFill.setEnabled(true);
    }//GEN-LAST:event_jradOvalActionPerformed

    private void jradLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradLineActionPerformed
        jradFill.setEnabled(false);
    }//GEN-LAST:event_jradLineActionPerformed

    private void jbtnShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnShapeActionPerformed
        jbtnEraser.setBackground(colorOld);
        jbtnPen.setBackground(colorOld);
        jbtnShape.setBackground(Color.GREEN);
        
        jpnPaint.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        turnOnOffJRadio(true);
        jsldSize.setValue(1);
        flagPen = false;
        flagEraser = false;
        flagShape = true;
    }//GEN-LAST:event_jbtnShapeActionPerformed

    private void jradFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradFillActionPerformed
        jradLine.setEnabled(false);
    }//GEN-LAST:event_jradFillActionPerformed

    private void jradDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradDrawActionPerformed
       jradLine.setEnabled(true);
    }//GEN-LAST:event_jradDrawActionPerformed

    private void jpnPaintMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPaintMouseReleased
        if(flagShape)
        {
            p2 = evt.getPoint();
            g.setColor(c);
            Graphics2D g1 = (Graphics2D) g;
            g1.setStroke(new BasicStroke(jsldSize.getValue()));

            if (jradLine.isSelected())
            {
                g.drawLine(p1.x, p1.y, p2.x, p2.y);
            }

            if (jradRectangle.isSelected()) 
            {
                int left = Math.min(p1.x, p2.x);
                int top = Math.min(p1.y, p2.y);
                int w = Math.abs(p1.x - p2.x);
                int h = Math.abs(p1.y - p2.y);

                if (jradDraw.isSelected()) 
                {
                    g.drawRect(left, top, w, h);
                } 
                else 
                {
                    g.fillRect(left, top, w, h);
                }
            }

            if (jradRoundRec.isSelected()) 
            {
                int left = Math.min(p1.x, p2.x);
                int top = Math.min(p1.y, p2.y);
                int w = Math.abs(p1.x - p2.x);
                int h = Math.abs(p1.y - p2.y);

                if (jradDraw.isSelected()) 
                {
                    g.drawRoundRect(left, top, w, h, 40, 45);
                } 
                else 
                {
                    g.fillRoundRect(left, top, w, h, 40, 45);
                }
            }

            if (jradOval.isSelected())
            {
                int left = Math.min(p1.x, p2.x);
                int top = Math.min(p1.y, p2.y);
                int w = Math.abs(p1.x - p2.x);
                int h = Math.abs(p1.y - p2.y);

                if (jradDraw.isSelected()) 
                {
                    g.drawOval(left, top, w, h);
                } 
                else
                {
                    g.fillOval(left, top, w, h);
                }
            }

            p1 = null;
            p2 = null;
        }
    }//GEN-LAST:event_jpnPaintMouseReleased

    private void jpnPaintMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnPaintMouseMoved
        jLabel1.setText("Point: " + evt.getPoint().x + ", " + evt.getPoint().y);
    }//GEN-LAST:event_jpnPaintMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnEraser;
    private javax.swing.JButton jbtnPen;
    private javax.swing.JButton jbtnShape;
    private javax.swing.JPanel jpnPaint;
    private javax.swing.JRadioButton jradDraw;
    private javax.swing.JRadioButton jradFill;
    private javax.swing.JRadioButton jradLine;
    private javax.swing.JRadioButton jradOval;
    private javax.swing.JRadioButton jradRectangle;
    private javax.swing.JRadioButton jradRoundRec;
    private javax.swing.JSlider jsldSize;
    private javax.swing.JButton jtbnChooseColor;
    // End of variables declaration//GEN-END:variables
}
